<?xml version="1.0"?>
<!DOCTYPE RomBuildSet  [	
  <!ELEMENT RomBuildSet (Rom+)>
  <!ATTLIST RomBuildSet name CDATA #REQUIRED
                        revision CDATA #REQUIRED
  >
    
  <!ELEMENT Rom (InFile+,Macro*,ImageFile,XMLFile)>
  <!ATTLIST Rom name CDATA #REQUIRED
		TargetBoard CDATA #REQUIRED
  >  
  
  <!ELEMENT InFile EMPTY>  
  <!ATTLIST InFile name CDATA #REQUIRED>
	
  <!ELEMENT XMLFile EMPTY>  
  <!ATTLIST XMLFile name CDATA #REQUIRED>
    
  <!ELEMENT Macro EMPTY>  
  <!ATTLIST Macro name CDATA #REQUIRED
		value CDATA #IMPLIED
  >

  <!ELEMENT ImageFile EMPTY>
  <!ATTLIST ImageFile name CDATA #REQUIRED>
]>

<RomBuildSet name="RomSet" revision="1">

    	<Rom name="H4 SmokeTest Temp" TargetBoard="h4hrp">	 
      	<InFile name="gtc_standard_h4"/>
            <InFile name="smoketests"/>
            <InFile name="sysstartconfig.iby"/>
            <InFile name="sysstart.iby"/>
            <Macro name="_STARTUPMODE1" value=""/>
            <Macro name="_EABI" value="ARMV5"/>
		<ImageFile name="h4hrp_smoketest_autorom_temp.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
        <Rom name="H6 SmokeTest Temp " TargetBoard="H6">
            <InFile name="gtc_standard_h6"/>
		<InFile name="smoketests"/>
            <InFile name="sysstart.iby"/>
            <InFile name="sysstartconfig.iby"/>    
            <Macro name="_STARTUPMODE1" value=""/>
            <Macro name="_EABI" value="ARMV5"/>
		<ImageFile name="h6_smoketest_autorom_temp.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
       <Rom name="NE1 SmokeTest Temp" TargetBoard="NE1">
		<InFile name="smoketests"/>
            <InFile name="gtc_standard_NE1"/>
            <InFile name="sysstart.iby"/>
            <InFile name="sysstartconfig.iby"/>           
            <Macro name="_STARTUPMODE1" value=""/>
            <Macro name="_EABI" value="ARMV5"/>
		<ImageFile name="NE1_smoketest_autorom_temp.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
      <Rom name="NE1S SmokeTest Temp" TargetBoard="NE1S">
		<InFile name="smoketests"/>
		<InFile name="gtc_standard_NE1S"/>
          	<InFile name="sysstart.iby"/>
         	<InFile name="sysstartconfig.iby"/>   
          	<Macro name="_STARTUPMODE1" value=""/>
          	<Macro name="_EABI" value="ARMV5"/>
		<ImageFile name="NE1S_smoketest_autorom_temp.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	 
</RomBuildSet>

